sudo: required

language: bash

env:
    - FLAKE8=false
    - FLAKE8=true

install:
    # Dependencies
    - sudo apt-get -qq update
    - sudo pip install --upgrade -qq pip
    - sudo apt-get -qq install cdparanoia cdrdao flac libcdio-dev libiso9660-dev libsndfile1-dev python-gobject python-musicbrainzngs python-mutagen python-setuptools sox swig
    - sudo pip install pycdio requests

    # Testing dependencies
    - sudo apt-get -qq install python-twisted-core
    - sudo pip install flake8

    # Build bundled C utils
    - cd src
    - sudo make install
    - cd ..

    # Installing
    - sudo python setup.py install

script:
    - if [ ! "$FLAKE8" = true ]; then python -m unittest discover; fi
    - if [ "$FLAKE8" = true ]; then flake8 --benchmark --statistics; fi
